proxy_host = "proxy-us.intel.com"
proxy_port = "911"
host_ip    = "10.10.10.102"

Vagrant::Config.run do |config|
  config.vm.host_name = "devstack-heat"
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.customize ["modifyvm", :id, "--memory", 6048]
  config.vm.forward_port 80, 8080,  :auto => true
  config.vm.forward_port 8081, 8081, :auto => true
  #config.vm.boot_mode='gui'

  #config.vm.provision :shell, :path=> "bootstrap.sh" 
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "../modules"
    puppet.manifest_file = "vagrant.pp"
    puppet.options = ["--verbose", "--node_name_value", config.vm.host_name, "--http_proxy_host", proxy_host, "--http_proxy_port", proxy_port ]
  end
end
