# -*- mode: ruby -*-
# vi: set ft=ruby :

def Kernel.is_windows?
    # Detect if we are running on Windows
    processor, platform, *rest = RUBY_PLATFORM.split("-")
    platform == 'mingw32'
end

proxy_host = "192.168.2.30"
proxy_port = "3128"
host_ip    = "10.10.10.102"
ssh_dir    = "~/.ssh/"

Vagrant::Config.run do |config|
  config.vm.host_name = "devstack-heat.mylocalnet.com"
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.customize ["modifyvm", :id, "--memory", 4096]
  # expose services
  config.vm.forward_port 80, 8888
  config.vm.forward_port 22,  2299 
  config.vm.forward_port 3333, 3333
  config.vm.forward_port 35357, 35357
  config.vm.forward_port 5000, 5000
  config.vm.forward_port 8000, 8000
  config.vm.forward_port 8004, 8004
  config.vm.forward_port 8080, 8080
  config.vm.forward_port 8773, 8773
  config.vm.forward_port 8774, 8774
  config.vm.forward_port 8776, 8776
  config.vm.forward_port 8777, 8777
  config.vm.forward_port 9292, 9292
  config.vm.forward_port 9696, 9696
  config.vm.forward_port 27017, 27017
  config.vm.forward_port 3306, 3306 
  config.vm.network :hostonly, host_ip
  #config.vm.boot_mode='gui'
  
  if !Kernel.is_windows?
      config.vm.share_folder("v-ssh", "/home/vagrant/.host-ssh", ssh_dir)
  end
  config.vm.provision :shell, :path => "bootstrap.sh" 
  config.vm.provision :puppet do |puppet|
  puppet.manifests_path = "manifests"
    puppet.module_path = "../modules"
    puppet.manifest_file = "vagrant.pp"
    puppet.options = ["--verbose", "--node_name_value", config.vm.host_name, "--http_proxy_host", proxy_host, "--http_proxy_port", proxy_port ]
  end
end
